project:
  resources: ["images"]
  type: website
  output-dir: docs

website:
  title: "AJ Averett"
  favicon: images\favicon.png
  
  description: "Senior Consultant at Booz Allen & Adjunct Faculty at MTECH"
  site-url: "https://ajaverett.com" 
  open-graph: true
  twitter-card: true

  navbar:
    background: "#0f172a"
    foreground: light
    pinned: true
    collapse: true

    left:
      - text: "Home"
        href: index.qmd
      - href: "about.qmd"
        text: About
      - href: "posts.qmd"
        text: Posts
      - href: "blocks.qmd"
        text: Blocks

    # RIGHT SIDE: Icons & Search
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ajaverett
        aria-label: "LinkedIn"
      - icon: github
        href: https://github.com/ajaverett
        aria-label: "GitHub"
      - icon: bi-file-earmark-person-fill      
        href: resume.pdf
        aria-label: "Resume"

format:
  html:
    theme: cosmo
    # css: styles.css
